"""add s3_key to statements

Revision ID: 2e4283b5c2c0
Revises: 1a692e0198cc
Create Date: 2026-04-27 10:05:51.078768

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2e4283b5c2c0"
down_revision: Union[str, Sequence[str], None] = "1a692e0198cc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("statements", sa.Column("s3_key", sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("statements", "s3_key")
    # ### end Alembic commands ###
