"""add file_hash to statements

Revision ID: a313d60314a7
Revises: 2e4283b5c2c0
Create Date: 2026-05-04 15:38:46.873885

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a313d60314a7"
down_revision: Union[str, Sequence[str], None] = "2e4283b5c2c0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("statements", sa.Column("file_hash", sa.String(), nullable=False))
    op.create_unique_constraint(None, "users", ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="unique")
    op.drop_column("statements", "file_hash")
    # ### end Alembic commands ###
